/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module au_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] led,
    input usb_rx,
    output reg usb_tx,
    output reg [23:0] io_led,
    output reg [7:0] io_seg,
    output reg [3:0] io_sel,
    input [4:0] io_button,
    input [23:0] io_dip
  );
  
  
  
  reg rst;
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_1 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  reg [15:0] M_temp_a_d, M_temp_a_q = 1'h0;
  reg [15:0] M_temp_b_d, M_temp_b_q = 1'h0;
  reg [29:0] M_timera_d, M_timera_q = 1'h0;
  reg [29:0] M_timerb_d, M_timerb_q = 1'h0;
  reg [29:0] M_timer_d, M_timer_q = 1'h0;
  localparam SELECT_state = 2'd0;
  localparam MANUAL_state = 2'd1;
  localparam TESTADD_state = 2'd2;
  localparam TESTSUB1_state = 2'd3;
  
  reg [1:0] M_state_d, M_state_q = SELECT_state;
  wire [7-1:0] M_seg_seg;
  wire [4-1:0] M_seg_sel;
  reg [20-1:0] M_seg_values;
  multi_seven_seg_2 seg (
    .clk(clk),
    .rst(rst),
    .values(M_seg_values),
    .seg(M_seg_seg),
    .sel(M_seg_sel)
  );
  
  reg [15:0] a;
  
  reg [15:0] b;
  
  reg [15:0] alu;
  
  wire [1-1:0] M_alu_comp_z;
  wire [1-1:0] M_alu_comp_v;
  wire [1-1:0] M_alu_comp_n;
  wire [16-1:0] M_alu_comp_alu;
  reg [6-1:0] M_alu_comp_alufn;
  reg [16-1:0] M_alu_comp_a;
  reg [16-1:0] M_alu_comp_b;
  alu_3 alu_comp (
    .alufn(M_alu_comp_alufn),
    .a(M_alu_comp_a),
    .b(M_alu_comp_b),
    .z(M_alu_comp_z),
    .v(M_alu_comp_v),
    .n(M_alu_comp_n),
    .alu(M_alu_comp_alu)
  );
  
  always @* begin
    M_state_d = M_state_q;
    M_timera_d = M_timera_q;
    M_timerb_d = M_timerb_q;
    M_timer_d = M_timer_q;
    M_temp_a_d = M_temp_a_q;
    M_temp_b_d = M_temp_b_q;
    
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    usb_tx = usb_rx;
    led = 8'h00;
    io_led = 24'h000000;
    io_seg = 8'hff;
    io_sel = 4'hf;
    M_seg_values[15+4-:5] = 4'h0;
    M_seg_values[10+4-:5] = 4'h0;
    M_seg_values[5+4-:5] = 4'h0;
    M_seg_values[0+4-:5] = 4'h0;
    io_sel = 4'hf;
    M_alu_comp_alufn = 6'h00;
    M_alu_comp_a = 16'h0000;
    M_alu_comp_b = 16'h0000;
    
    case (M_state_q)
      SELECT_state: begin
        M_seg_values[15+4-:5] = 3'h5;
        M_seg_values[10+4-:5] = 4'he;
        M_seg_values[5+4-:5] = 4'hd;
        M_seg_values[0+4-:5] = 5'h1f;
        io_seg = ~M_seg_seg;
        io_sel = ~M_seg_sel;
        if (io_dip[0+0+0-:1]) begin
          if (io_button[1+0-:1]) begin
            M_state_d = TESTADD_state;
          end
        end else begin
          if (io_button[1+0-:1]) begin
            M_state_d = MANUAL_state;
          end
        end
      end
      MANUAL_state: begin
        M_seg_values[15+4-:5] = 5'h1e;
        M_seg_values[10+4-:5] = 5'h1e;
        M_seg_values[5+4-:5] = 5'h1e;
        M_seg_values[0+4-:5] = 5'h1e;
        io_seg = ~M_seg_seg;
        io_sel = ~M_seg_sel;
        if (io_dip[0+1+0-:1]) begin
          a[0+7-:8] = io_dip[8+7-:8];
          a[8+7-:8] = io_dip[16+7-:8];
          if (io_button[1+0-:1]) begin
            M_temp_a_d = a;
          end
        end else begin
          b[0+7-:8] = io_dip[8+7-:8];
          b[8+7-:8] = io_dip[16+7-:8];
          if (io_button[1+0-:1]) begin
            M_temp_b_d = b;
          end
        end
        M_alu_comp_alufn = io_dip[0+2+5-:6];
        M_alu_comp_a = M_temp_a_q;
        M_alu_comp_b = M_temp_b_q;
        io_led[8+7-:8] = M_alu_comp_alu[0+7-:8];
        io_led[16+7-:8] = M_alu_comp_alu[8+7-:8];
        io_led[0+0+0-:1] = M_alu_comp_z;
        io_led[0+1+0-:1] = M_alu_comp_v;
        io_led[0+2+0-:1] = M_alu_comp_n;
        if (io_button[2+0-:1]) begin
          M_state_d = SELECT_state;
        end
      end
      TESTADD_state: begin
        M_alu_comp_alufn = 6'h00;
        a = 16'h57aa;
        M_alu_comp_a = a;
        b = 16'h2124;
        M_alu_comp_b = b;
        alu = M_alu_comp_alu;
        if (M_timera_q[29+0-:1]) begin
          io_led[0+7+0-:1] = 1'h1;
          io_led[8+7-:8] = b[0+7-:8];
          io_led[16+7-:8] = b[8+7-:8];
          M_timerb_d = M_timerb_q + 1'h1;
          M_seg_values[15+4-:5] = 4'ha;
          M_seg_values[10+4-:5] = 4'hb;
          M_seg_values[5+4-:5] = 4'hb;
          M_seg_values[0+4-:5] = 5'h1f;
          io_seg = ~M_seg_seg;
          io_sel = ~M_seg_sel;
        end else begin
          io_led[0+6+0-:1] = 1'h1;
          io_led[8+7-:8] = a[0+7-:8];
          io_led[16+7-:8] = a[8+7-:8];
          M_timera_d = M_timera_q + 1'h1;
          M_seg_values[15+4-:5] = 4'ha;
          M_seg_values[10+4-:5] = 4'hb;
          M_seg_values[5+4-:5] = 4'hb;
          M_seg_values[0+4-:5] = 5'h1f;
          io_seg = ~M_seg_seg;
          io_sel = ~M_seg_sel;
        end
        if (M_timerb_q[29+0-:1]) begin
          io_led[0+7+0-:1] = 1'h0;
          M_timer_d = M_timer_q + 1'h1;
          if (io_dip[0+7+0-:1]) begin
            M_alu_comp_a = a + 1'h1;
          end
          io_led[8+7-:8] = alu[0+7-:8];
          io_led[16+7-:8] = alu[8+7-:8];
          io_led[0+0+0-:1] = M_alu_comp_z;
          io_led[0+1+0-:1] = M_alu_comp_v;
          io_led[0+2+0-:1] = M_alu_comp_n;
          if (alu == 16'h78ce) begin
            M_seg_values[15+4-:5] = 5'h11;
            M_seg_values[10+4-:5] = 4'ha;
            M_seg_values[5+4-:5] = 3'h5;
            M_seg_values[0+4-:5] = 3'h5;
            io_seg = ~M_seg_seg;
            io_sel = ~M_seg_sel;
          end else begin
            M_seg_values[15+4-:5] = 4'hc;
            M_seg_values[10+4-:5] = 4'ha;
            M_seg_values[5+4-:5] = 1'h1;
            M_seg_values[0+4-:5] = 4'hd;
            io_seg = ~M_seg_seg;
            io_sel = ~M_seg_sel;
          end
        end
        if (io_button[3+0-:1]) begin
          M_timer_d = 30'h00000000;
          M_timera_d = 30'h00000000;
          M_timerb_d = 30'h00000000;
          M_state_d = SELECT_state;
        end
        if (io_button[4+0-:1] | M_timer_q[29+0-:1] == 1'h1) begin
          M_timer_d = 30'h00000000;
          M_timera_d = 30'h00000000;
          M_timerb_d = 30'h00000000;
          M_state_d = TESTSUB1_state;
        end
        if (io_button[2+0-:1]) begin
          M_timer_d = 30'h00000000;
          M_timera_d = 30'h00000000;
          M_timerb_d = 30'h00000000;
          M_state_d = SELECT_state;
        end
      end
      TESTSUB1_state: begin
        M_alu_comp_alufn = 6'h01;
        a = 16'hc030;
        M_alu_comp_a = a;
        b = 16'h0c8b;
        M_alu_comp_b = b;
        alu = M_alu_comp_alu;
        if (M_timera_q[29+0-:1] & ~(M_timer_q)) begin
          io_led[0+7+0-:1] = 1'h1;
          io_led[8+7-:8] = b[0+7-:8];
          io_led[16+7-:8] = b[8+7-:8];
          M_timerb_d = M_timerb_q + 1'h1;
          M_seg_values[15+4-:5] = 3'h5;
          M_seg_values[10+4-:5] = 4'hf;
          M_seg_values[5+4-:5] = 5'h10;
          M_seg_values[0+4-:5] = 1'h1;
          io_seg = ~M_seg_seg;
          io_sel = ~M_seg_sel;
        end else begin
          io_led[0+6+0-:1] = 1'h1;
          io_led[8+7-:8] = a[0+7-:8];
          io_led[16+7-:8] = a[8+7-:8];
          M_timera_d = M_timera_q + 1'h1;
          M_seg_values[15+4-:5] = 3'h5;
          M_seg_values[10+4-:5] = 4'hf;
          M_seg_values[5+4-:5] = 5'h10;
          M_seg_values[0+4-:5] = 1'h1;
          io_seg = ~M_seg_seg;
          io_sel = ~M_seg_sel;
        end
        if (M_timerb_q[29+0-:1]) begin
          io_led[0+7+0-:1] = 1'h0;
          M_timer_d = M_timer_q + 1'h1;
          if (io_dip[0+7+0-:1]) begin
            M_alu_comp_a = a + 1'h1;
          end
          io_led[8+7-:8] = alu[0+7-:8];
          io_led[16+7-:8] = alu[8+7-:8];
          io_led[0+0+0-:1] = M_alu_comp_z;
          io_led[0+1+0-:1] = M_alu_comp_v;
          io_led[0+2+0-:1] = M_alu_comp_n;
          if (alu == 16'hb3a5 & M_alu_comp_n == 1'h1) begin
            M_seg_values[15+4-:5] = 5'h11;
            M_seg_values[10+4-:5] = 4'ha;
            M_seg_values[5+4-:5] = 3'h5;
            M_seg_values[0+4-:5] = 3'h5;
            io_seg = ~M_seg_seg;
            io_sel = ~M_seg_sel;
          end else begin
            M_seg_values[15+4-:5] = 4'hc;
            M_seg_values[10+4-:5] = 4'ha;
            M_seg_values[5+4-:5] = 1'h1;
            M_seg_values[0+4-:5] = 4'hd;
            io_seg = ~M_seg_seg;
            io_sel = ~M_seg_sel;
          end
        end
        if (io_button[3+0-:1]) begin
          M_timer_d = 30'h00000000;
          M_timera_d = 30'h00000000;
          M_timerb_d = 30'h00000000;
          M_state_d = TESTADD_state;
        end
        if (io_button[4+0-:1] | M_timer_q[29+0-:1] == 1'h1) begin
          M_timer_d = 30'h00000000;
          M_timera_d = 30'h00000000;
          M_timerb_d = 30'h00000000;
          M_state_d = SELECT_state;
        end
        if (io_button[2+0-:1]) begin
          M_timer_d = 30'h00000000;
          M_timera_d = 30'h00000000;
          M_timerb_d = 30'h00000000;
          M_state_d = SELECT_state;
        end
      end
    endcase
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_temp_a_q <= 1'h0;
      M_temp_b_q <= 1'h0;
      M_timera_q <= 1'h0;
      M_timerb_q <= 1'h0;
      M_timer_q <= 1'h0;
      M_state_q <= 1'h0;
    end else begin
      M_temp_a_q <= M_temp_a_d;
      M_temp_b_q <= M_temp_b_d;
      M_timera_q <= M_timera_d;
      M_timerb_q <= M_timerb_d;
      M_timer_q <= M_timer_d;
      M_state_q <= M_state_d;
    end
  end
  
endmodule
